.PHONY: clean All

All:
	@echo "----------Building project:[ nwthpool - Debug ]----------"
	@cd "nwthpool" && "$(MAKE)" -f  "nwthpool.mk"
clean:
	@echo "----------Cleaning project:[ nwthpool - Debug ]----------"
	@cd "nwthpool" && "$(MAKE)" -f  "nwthpool.mk" clean
